# @author : Julien Pechberty
#
# https:/za/help.github.com/en/actiofnsdd
name: JAVA TD 5 - Tests runners
on:
  push:
    branches:
      - main
jobs:
  run-test:
    name : Run Tests suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java-version: [22]

    steps:
      - name: Starting RUNNER
        run: echo "Launching tests for JAVA ${{ matrix.java-version }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Run tests with Maven
        run: mvn test -Dsurefire.printSummary=true